### PR TITLE
fix multi-lines vanishing when exiting edit mode

### LINKED ISSUE #163: Blank newlines disappear on text area defocus
Sections C and D have one blank newline in-between them.

Sections A, B, and C also had 1 blank newline separating them. However, when I defocus the text area, these 3 newlines disappear:

image

Using the latest version of SpecEd:

image

For clarity, here is how my text area looks before I defocus:
 
image

### PR DESCRIPTION
**Pull request by mdaxtman**
@bmathews fixes #163 

2 issues were present with this bug. Eating of empty lines when exiting edit mode and eating of multi-line list items when exiting out of edit mode. 

before--
screen shot 2016-08-29 at 11 12 50 am

after--
screen shot 2016-08-29 at 11 12 28 am

### CODE REVIEW

File: app/components/canvas/element-types/text-element/text-content-editor.js [hunk 1]
```diff
@@ -206,21 +229,40 @@ export default class TextContentEditor extends Component {
...
-        {text.map((element, i) => (
-          <li
-            className={
-             `${classNames.line}`
+        {text.map((li, i) => {
+          let listItem = li;
+          const lines = [];
+          let line = "";
+
+          while (listItem.length) {
```
Comment (rgerstenberger) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: This is an interesting `while` loop here. @bmathews would this be better as a `reduce`?

File: app/components/canvas/element-types/text-element/text-content-editor.js [hunk 2]
```diff
@@ -48,19 +48,43 @@ export default class TextContentEditor extends Component {
...
+        });
+
+        return child.innerText;
+      }
+
+      if (!child.children.length) {
+        return child.innerText.replace(/\n$/, "") || "";
+      }
+
+      return Array.prototype.map.call(child.children, (line) => line.innerText.replace(/\n$/, ""));
```
Comment (rgerstenberger) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: What's the reasoning for `Array.prototype.method` here and above? Wouldn't `child.children.map` work?

Comment (mdaxtman) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: just double-checked. No it won't. One of those instances where it's an "array-like" element list, but there is no access to the array methods.

File: app/components/canvas/element-types/text-element/text-content-editor.js [hunk 3]
```diff
@@ -48,19 +48,43 @@ export default class TextContentEditor extends Component {
...
     }
 
-    const nextChildren = Array.prototype.map.call(this.editor.childNodes, (child) => (
-      child.innerText || ""
-    ));
+    const nextChildren = Array.prototype.map.call(this.editor.childNodes, (child) => {
+      if (listType) {
+        const { children: childElements } = child;
+
+        Array.prototype.forEach.call(child.children, (line, i) => {
```
Comment (rgerstenberger) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: Here you're mutating the array that you're iterating over, which is usually a bad idea. It's even more confusing because you rename `child.children` to `childElements` but then use `child.children` on line 72 and 75.  Work with @bmathews to refactor this, you may need to deep clone `child.children`.

File: app/components/canvas/element-types/text-element/text-content-editor.js (hunk 2 above)
Comment (rgerstenberger) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: Gotcha, sounds good.

**Comment by mdaxtman** [comment]
@rgerstenberger Refactored to use `reduce` instead of the `while` loop.

File: app/components/canvas/element-types/text-element/text-content-editor.js [hunk 4]
```diff
@@ -206,21 +229,38 @@ export default class TextContentEditor extends Component {
...
       >
-        {text.map((element, i) => (
-          <li
-            className={
-             `${classNames.line}`
+        {text.map((li, i) => {
+          let line = "";
+
+          const string = li.split("").reduce((lines, character) => {
+            if (character === "\n") {
```
Comment (rgerstenberger) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: Would this ever get hit? I would assume `character` to be a single character e.g. `\` or `n` not the combination of the two.

File: app/components/canvas/element-types/text-element/text-content-editor.js [hunk 5]
```diff
@@ -206,21 +229,38 @@ export default class TextContentEditor extends Component {
...
+              lines.push(line);
+              line = "";
```
Comment (rgerstenberger) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: at this point `line === ""` from line 236. So we're pushing an empty string on `lines` and resetting that empty string to an empty string?

File: app/components/canvas/element-types/text-element/text-content-editor.js (hunk 4 above)
Comment (bmathews) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: it does count as one character

image

File: app/components/canvas/element-types/text-element/text-content-editor.js (hunk 5 above)
Comment (rgerstenberger) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: Oh, `line` is storing state for this loop. I feel like this `reduce` could be handled differently. Maybe a split on `\n` instead of `""`? Work with @bmathews to get this into a clearer code path.

File: app/components/canvas/element-types/text-element/text-content-editor.js (hunk 4 above)
Comment (mdaxtman) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: yeah, that surprised me when I found that out as well.

File: app/components/canvas/element-types/text-element/text-content-editor.js (hunk 5 above)
Comment (mdaxtman) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: that's what we were doing before was splitting on the line breaks, which was one of the reasons for the bugs. If we have something like `"lines\n\n\nhere\n"` then splitting it would treat the breaks as individual lines rather than the end of the line, hence the reason for the `while` loop which I refactored to `reduce`. 

So in this instance, `contenteditable` would count the string above as one line with content, two empty lines, one line with content, end of line. 

Splitting on the breaks treats it like one line of content, two empty lines, one line of content, one empty line. 

screen shot 2016-08-29 at 12 09 46 pm

It's simply how `contenteditable` inserts the breaks, and I had to figure out how to work with it.

Comment (bmathews) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: @mdaxtman  But `element.replace(/\n$/, "").split("\n")` removed the last `\n`, then split on `\n`, right?

Comment (mdaxtman) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: @bmathews, correct, I've revised accordingly.

File: app/components/canvas/element-types/text-element/text-content-editor.js [hunk 6]
```diff
@@ -48,19 +48,43 @@ export default class TextContentEditor extends Component {
...
+          if (!line.children.length && !line.innerText.length && line.localName === "div") {
+            childElements[i].innerText = "\n";
+          }
+        });
+
+        return child.innerText.replace(/\n$/, "");
+      }
+
+      if (!child.children.length) {
+        return child.innerText.replace(/\n$/, "") || "";
```
Comment (bmathews) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: what's the `||` here helping to catch?

Comment (mdaxtman) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: honestly, I don't recall. That was part of the old code from when I originally built this. I put that there for a reason. I can remove and test.

File: app/components/canvas/element-types/text-element/text-content-editor.js [hunk 7]
```diff
@@ -48,19 +48,43 @@ export default class TextContentEditor extends Component {
...
-      nextChildren,
+      nextChildren.reduce((arr, child) => {
+        if (Array.isArray(child)) {
+          return arr.concat(child);
+        }
+
+        arr.push(child);
+
+        return arr;
+      }, []),
```
Comment (bmathews) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: isn't `nextChildren` here always an array of strings? When would an item in it be an array?

File: app/components/canvas/element-types/text-element/text-content-editor.js (hunk 6 above)
Comment (bmathews) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: The result of `child.innerText.replace(/\n$/, "")` will never be anything other than a string, empty or not. So you should be fine to remove it.

File: app/components/canvas/element-types/text-element/text-content-editor.js (hunk 7 above)
Comment (mdaxtman) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: @bmathews on line 75, it returns the mapped array of child elements' text.

Comment (bmathews) [inline app/components/canvas/element-types/text-element/text-content-editor.js]: `lodash.flatten(nextChildren)` should work, then!

**Comment by bmathews** [comment]
Dependent on a spectacle-editor-viewer release, will :shipit: once that's ready

**Comment by mdaxtman** [comment]
viewer PR looks good. 👍
